_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "8":
                - 1
                - 5
            "12": 0.18.6
            "13": darwin-arm64
alpha:
    value: 0.001
hidden_layer_sizes:
    value:
        - 50
        - 50
        - 25
learning_rate:
    value: invscaling
learning_rate_init:
    value: 0.0001
